package com.example.skillsync.data.network.generated

enum class ApiCredential(val apiKey: String, val userName: String, val userPass: String, val userRole: String) {
    ADDTRAINERSKILLIDP("255", "AISHWAR_AddTrainerSkill", "2bd6UhV#PJ#T", "Add Trainer Skill (IDP)"),
    ASSIGNMENTAPI("15", "AISHWAR_AssignmentAPI", "4PV6aCe6Sc8!", "Assignment API"),
    CHECKCOURSEAVAILABILITYINRMS("111", "AISHWAR_TrainerRCSchedu", "jGErt8!Agr\$a", "Trainer RC Schedule"),
    CHECKCOURSEAVAILABILITYINRMS2("104", "AISHWAR_CheckCourseAvai", "\$3GapuDUF5XU", "Check Course Availability in RMS"),
    COURSEANDTECHNOLOGYLIST("114", "AISHWAR_CourseTechnolog", "L5PMuN!wKE4j", "Course & Technology List"),
    COURSELIST("164", "AISHWAR_CourseList", "@56Crxj#Yc@5", "Course List"),
    COURSEWHITOUTEXAM("213", "AISHWAR_CourseWhitoutEx", "V9n82gfmC\$\$W", "Course Whitout Exam"),
    EXAMCOURSELINKEDAPI("215", "AISHWAR_ExamCourseLinke", "K7!k@n3dA\$w2", "Exam Course Linked API"),
    GETACTIVESCDATE("13", "AISHWAR_GetActiveSCDate", "P2mbqrhB#t4F", "Get Active SC Date"),
    GETASSIGNMENTPAX("209", "AISHWAR_GetAssignmentpa", "!zSgxaRdA9dC", "Get Assignment pax"),
    GETCOURSEANDDOMAIN("205", "AISHWAR_GetCourseandDom", "HcUAr7!5zALS", "Get Course and Domain"),
    GETCOURSECONTENTURL("156", "AISHWAR_GetCourseConten", "3!SDHwJvBn2w", "Get Course Content URL"),
    GETCOURSEMODULE("206", "AISHWAR_GetCourseModule", "NpT5tqde@TZ2", "Get Course Module"),
    GETCOURSENAME("70", "AISHWAR_GetCourseName", "H7GnTdC@ECvC", "Get Course Name"),
    GETCOURSESCHEDULE("246", "AISHWAR_GetCourseSchedu", "tFEy8T6JLT!J", "Get Course Schedule"),
    GETCOURSESYLLABUSTOC("248", "AISHWAR_GetCourseSyllab", "W@PFkUQt\$Ek3", "Get Course Syllabus TOC"),
    GETDIRECTINDIRECTREPORTEE("82", "AISHWAR_GetDirectIndire", "3R\$Nc7ThBX64", "Get Direct Indirect Reportee"),
    GETHRINCIDENTPOSITIVENEGATIVE("59", "AISHWAR_GetHRIncidentPo", "42nLmM!#weDk", "Get HR Incident Positive Negative"),
    GETINHOUSEANDFLTRAINERSOFCOURSES("157", "AISHWAR_GetInhouseandFL", "2XC!2LBpsTJh", "Get Inhouse and FL Trainers Of Courses"),
    GETLATESTVERSIONOFCOURSES("172", "AISHWAR_GetLatestVersio", "M@bXLcQ4h!@\$", "Get Latest Version Of Courses"),
    GETNEGATIVEFEEDBACKCOUNT("58", "AISHWAR_GetNegativeFeed", "#9u7@@hAHWUg", "Get Negative Feedback Count"),
    GETRECORDINGDETAILSBYASSIGNMENTID("278", "AISHWAR_GetRecordingDet", "RPtPvRq5nF\$H", "Get Recording Details by Assignment Id"),
    GETSCID("173", "AISHWAR_GetSCID", "kLH#4T!Tfu6f", "Get SCID"),
    GETTRAINERDETAILS("75", "AISHWAR_GetTrainerDetai", "7zCheFM\$Cc\$t", "Get Trainer Details"),
    GETTRAINERFEEDBACKDETAILS("244", "AISHWAR_GetTrainerFeedb", "T9\$jsBnSW7Rd", "Get Trainer Feedback Details"),
    GETTRAINERFREESHEDULEANDDETAILS("171", "AISHWAR_GetTrainerFreeS", "J6FLKGx!exA7", "Get Trainer Free Shedule and Details"),
    GETTRAINERNEGATIVEFEEDBACK("218", "AISHWAR_GetTrainerNegat", "j34JFz\$s9Um#", "Get Trainer Negative Feedback"),
    GETTRAINERSKILLS("217", "AISHWAR_GetTrainerSkill", "dpcwt4L5\$@7U", "Get Trainer Skills"),
    GETTRAINERVENDERCERTIFICATIONCOUNT("57", "AISHWAR_GettrainerVende", "!\$R#gQuAs9Rw", "Get trainer Vender Certification Count"),
    GETUNIQUECERTIFICATIONSCOUNTVALUE("72", "AISHWAR_GetUniqueCertif", "G8!9P@\$m3t25", "Get Unique Certifications Count Value"),
    GETUTILIZATION("55", "AISHWAR_GetUtilization", "j4CakF7gEg#f", "Get Utilization"),
    PREVIOUSANDUPCOMMINGASSIGNMENTS("16", "AISHWAR_PreviousUpcommi", "J8LzP@HkW#Ve", "Previous & Upcomming Assignments"),
    TRAINERAVAILABILITY("90", "AISHWAR_Traineravailabi", "c2yRDVdG#XCs", "Trainer availability"),
    TRAINERLAST3MONTHSUTILIZATION("39", "AISHWAR_TrainerLast3Mon", "TmSe!9A!@GfL", "Trainer_Last_3_Months_Utilization"),
    TRAINERRESUMEDETAILS("87", "AISHWAR_TrainerResumeDe", "nw@dL3xQD#BL", "Trainer Resume Details"),
    UNALLOCATEDASSIGNMENT("190", "AISHWAR_UnallocatedAssi", "\$5djCU@w7eR3", "Unallocated Assignment"),
    UPCOMINGASSIGNMENTS("93", "AISHWAR_UpcomingAssignm", "nFY\$g68zSaRD", "Upcoming Assignments"),
}
